### PR TITLE
ci: test Go 1.9.x, 1.10.x and tip

### PR DESCRIPTION
**Pull request by smola**
More info:
https://github.com/src-d/guide/blob/master/engineering/conventions-go.md

Signed-off-by: Santiago M. Mola <santi@mola.io>

### CODE REVIEW

**Comment by mcuadros** [comment]
Personally, I consider `tip` as a waste or resources for TravisCI

**Comment by smola** [comment]
@mcuadros Just for the record, AFAIK, we can setup Travis to execute deploy only with one of them (I'd swear we did with gitquery or other project). On the other hand, it's true that for apps we don't care _that_ much about compatibility with older versions.

**Comment by mcarmonaa** [comment]
@smola what is the state of this PR? Is it expected to use only one version finally or it's ready to be merged?

On the other hand, should the versions [be between quotation marks](https://github.com/travis-ci/travis-ci/issues/9247) to avoid weird behaviors or it's ok as it is?

**Comment by smola** [comment]
Updated the PR: https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
@mcuadros see the updated PR, version used for deploy can be defined.

On the other hand, if we really want to drop support for older Go versions immediately for applications, we should update the guide accordingly.

**Comment by mcuadros** [comment]
@smola the guide says that we maintain old Go versions for binaries?

**Comment by smola** [comment]
@mcuadros It does not talk about libraries or binaries, but we should update it. In fact, after feedback on https://github.com/src-d/guide/pull/211 I would say that we don't want to put specific requirements for the toolchain an application is built with, just the operating system. So for libraries we want wide support (e.g. multiple Go versions, multiple Python versions, different C compilers) and for applications just what it makes more sense for us (e.g. latest stable Go version).

**Comment by smola** [comment]
Anyway. I'm closing this PR, since it is superseded by https://github.com/src-d/rovers/pull/181

**Pull request closed without merging**
