### PR TITLE
github: handle rate limit errors gracefully

### PR DESCRIPTION
**Pull request by smola**
When we find a rate limit error (403 code + X-RateLimit headers), instead
of failing, we wait and retry. Usually the rate limit error shouldn't be
hit.

This happens only if more than one process is accessing GitHub API
with the same token (as it happens with CI, but also in other cases).

Signed-off-by: Santiago M. Mola <santi@mola.io>

### CODE REVIEW

**Comment by smola** [comment]
Note that this fails with a timeout: https://travis-ci.org/src-d/rovers/jobs/380207044
Something like https://github.com/src-d/rovers/pull/184 would be needed to prevent these failures.

**Comment by dennwc** [comment]
@smola Why are we maintaining a custom Go Github client instead of using [the existing one](https://github.com/google/go-github)?

**Comment by smola** [comment]
@dennwc Honestly, I don't remember. I think that, when we started, we needed more adapter code to use the existing client than actually having a minimal client ourselves. It is definitely something we could review.

**Comment by dennwc** [comment]
The reason I'm asking is that this client handles everything including auth and retries on rate limit. So it might worth it to drop our code in favor of more established client library from Google.

**Comment by ajnavarro** [comment]
We were using a fork of the GitHub API modified to add MongoDB tags to the output model.

To avoid maintain that fork, we move from the fork to a custom call because we were using only one of the multiple calls to the API.

Since Go 1.8, we can cast structs that use the same params. We can move to the existing GitHub library now, but I don't think is a high priority.

**Comment by mcarmonaa** [comment]
I added an issue to not forget this matter

**Pull request merged**
