### PR TITLE
providers/bitbucket: skip mercurial repositories

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes https://github.com/src-d/borges/issues/326

### CODE REVIEW

**Comment by erizocosmico** [comment]
fixed

**Comment by mcarmonaa** [comment]
CI AppVeyor fails

**Comment by erizocosmico** [comment]
Yeah, but the error is on their side:

```
git clone --quiet --branch v1 --depth 1 https://github.com/src-d/ci.git .ci;
cd .ci && \
pwsh -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/smola/ci-tricks/master/get.ps1'))"
Exception calling "DownloadString" with "1" argument(s): "The remote server returned an error: (503) backend read error."
At line:1 char:1
+ iex ((New-Object System.Net.WebClient).DownloadString('https://raw.gi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : WebException
 
mingw32-make: *** [.ci/Makefile.main:215: prepare-services] Error 1
Command exited with code 2
```

**Comment by erizocosmico** [comment]
Now it has passed

**Pull request merged**
